name: Check new pull request

on:
  pull_request:
    types: [ opened ]

jobs:
  check_pr:
    uses: aiuta-com/aiuta-action/.github/workflows/check_pr_labels.yaml@main
    secrets:
      token: ${{ secrets.AIUTA_PERSONAL_ACCESS_TOKEN }}
